name: Convert POT to JSON
on:
  push:
    branches: l10n_develop
    paths:
      - 'languages/cocoon-*.pot'
  workflow_dispatch:

# 複数ジョブの同時実行を禁止
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  WP_POT_TO_JSON:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      id: setup_node_id
      with:
        node-version: 14
        cache: npm
    - name: Install po2json
      run: npm install po2json --save
    - name: Count translated POT
      id: translated_pot
      shell: bash
      run: |
        cd languages
        echo "count=$(ls cocoon-*.pot | wc -l)" >> $GITHUB_OUTPUT
    - name: Run po2json
      id: run_po2json
      shell: bash
      if: steps.translated_pot.outputs.count > 0
      run: |
        pwd
        cd languages
        ls cocoon-*.pot | sed -r 's/cocoon-//g' | sed -r 's/.pot//g' | xargs -I LOCALE ../node_modules/po2json/bin/po2json -f jed1.x ./cocoon-LOCALE.pot ./cocoon-LOCALE-cocoon-blocks-js.json
    - name: Create Pull Request
      if: steps.run_po2json.conclusion == 'success'
      uses: peter-evans/create-pull-request@v4
      with:
        add-paths: languages/*.json
        token: ${{ secrets.GITHUB_TOKEN }}
        base: master
        delete-branch: true
        title: "JSON Regenerated"
        commit-message: "JSON Regenerated"
        body: |
          JSON file regenerated by github actions
        branch: "pot-to-json-${{github.sha}}"