name: Generate POT file
on:
  # プッシュイベントがあった場合に起動
  push:
    # 指定したブランチに変更があった場合のみ起動
    branches: develop
    # 以下のパスのファイルに変更があった場合のみ起動
    paths:
      - blocks/src/**
  # 手動トリガ
  workflow_dispatch:

# 複数ジョブの同時実行を禁止
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  WP_POT_Generator:
    runs-on: ubuntu-latest
    env:
      SOURCE_POT: languages/cocoon.pot
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install wp-cli
      shell: bash
      run: |
        curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        chmod +x wp-cli.phar
        sudo mv wp-cli.phar /usr/bin/wp
    - name: Run make-pot
      shell: bash
      run: |
        wp i18n make-pot . $SOURCE_POT --exclude="languages/*,plugins/*,blocks/dist/*,node_modules/*" --skip-audit --ignore-domain
    - name: Count changes
      id: changes
      shell: bash
      run: |
        echo "count=$(git diff --name-only . | wc -l)" >> $GITHUB_OUTPUT
    - name: Commit and push
      shell: bash
      if: steps.changes.outputs.count > 0
      run: |
        git config --global user.name "GithubActions BOT"
        git config --global user.email "github-actions-bot@users.noreply.github.com"
        git config --global --add safe.directory "$GITHUB_WORKSPACE"

        git add $SOURCE_POT
        git commit -m "Generated POT File"
        git push "https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY"