name: Generate POT file
on:
  workflow_dispatch:
  push:
    branches: [master, develop]

jobs:
  WP_POT_Generator:
    runs-on: ubuntu-latest
    steps:
    - name: Wordpress POT Generation
      uses: actions/checkout@v3
      shell: bash
      run: |
        THEME_ROOT="/home/runner/work/cocoon/cocoon"
        SAVE_FULL_PATH="$THEME_ROOT/$SAVE_DIR/$DOMAIN.pot"

        # Download WP CLI
        curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        chmod +x wp-cli.phar
        sudo mv wp-cli.phar /usr/bin/wp

        # Regenerate POT file
        wp i18n make-pot "$THEME_ROOT" "$SAVE_FULL_PATH" --domain="$DOMAIN" --exclude="languages/*,plugins/*,blocks/dist/*,node_modules/*" --skip-audit --ignore-domain
      env:
        SAVE_DIR: 'languages'
        DOMAIN: 'cocoon'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        base: master
        delete-branch: true
        title: "POT Regenerated"
        branch: "feature/test-${{github.sha}}"